### ISSUE TITLE
访问控制可否加入域名列表

### ISSUE THREAD

**Issue by kangxicome** [xsm1997/love-and-peace#1]
现在只有IP，针对很多域名应用无法胜任。

**Comment by xsm1997** [comment]
因为一个域名可能对应多个IP，所以不能简单地通过添加IP来解决。要改就得大改。
目前可以提供一个自行修改的思路，在/etc/dnsmasq.ssr/里面可以添加dnsmasq规则列表，可以参照同文件夹内的gfwlist，借助dnsmasq来自动添加ipset列表，来完成域名代理。
暂时没有更新加入的计划，如果会更新加入的话，也是这个思路。

**Comment by kangxicome** [comment]
先自己改着，等后续可能的更新吧，谢
